### ISSUE TITLE
Can we add default commands?

### ISSUE THREAD

**Issue by wolph** [abraxxa/EventGhost-Onkyo-ISCP-plugin#1]
Thank for this plugin, this could be really useful for me.

Currently it's slightly difficult to use however, would it be possible to include the commands from this project as defaults? https://github.com/miracle2k/onkyo-eiscp

**Comment by abraxxa** [comment]
I was in contact with Onkyo when I started writing this plugin and they told me that I'll only get the codes if I'd sign an NDA.
So because of Onkyo's licensing I can't include any codes in my plugin, sorry.

**Comment by wolph** [comment]
Ah... that's annoying :(

Thanks for the quick response though. Maybe I can generate something myself in the mean time

**Comment by Ltek** [comment]
I have all the default commands in a nice clean XLS (fyi - they are posted all over the net)... I can provide them.

**Comment by abraxxa** [comment]
It's not that I'm not able to find them but its illegal to publish them.
Feel free to submit a pull request for a feature that lets you configure a separate file which holds a command to description mapping and an example for the UI how it has to look.
